- name: create {{ vnc }} user
  user: name={{ vnc }} comment="vnc user" generate_ssh_key=yes state=present password={{ password }} shell=/bin/bash

- name: authorize my SSH key to access {{ vnc }}
  authorized_key: user={{ vnc }} key="{{ lookup('file', '../files/ideus_rsa.pub') }}"

- name: copy ssh_config so that github doesn't do host verification
  action: copy src=ssh_config dest=~{{ vnc }}/.ssh/config owner={{ vnc }} group={{ vnc }}

- name: add {{ vnc }} to sudoers
  lineinfile: "dest=/etc/sudoers state=present line='%{{ vnc }} ALL=(ALL) NOPASSWD: ALL'"

# - name: require password upon each invocation of sudo
#   lineinfile: "dest=/etc/sudoers state=present line='Defaults timestamp_timeout=0'"

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh

- name: create www-data group
  group: name=www-data state=present

- name: create apps directory owned by {{ vnc }}:www-data with setgid bit
  # note: 2755 => 2=setgid, 7=owner rwx, 5=group rx, 5=other rx
  file: name=~{{ vnc }}/apps state=directory owner={{ vnc }} group=www-data mode=2755

# - name: remove authorized_keys for root (specifically for DigitalOcean)
#   file: name=/root/.ssh/authorized_keys state=absent
